import type { Metadata } from "next";
import Header from "./Header";
import "./globals.css";
import styles from "./page.module.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className={styles.page}>
          <Header />
          {children}
        </div>
      </body>
    </html>
  );
}
